apiVersion: v2
name: postgres-operator
version: 1.10.1
appVersion: 1.10.1
home: https://github.com/cybertec-postgresql/cybertec-pg-operator
description: Postgres Operator creates and manages PostgreSQL clusters running in Kubernetes
keywords:
- postgres
- operator
- cloud-native
- patroni
- spilo
maintainers:
- name: Zalando
  email: opensource@zalando.de
sources:
- https://github.com/cybertec-postgresql/cybertec-pg-operator
engine: gotpl
