apiVersion: v2
name: postgres-operator-ui
version: 1.9.0
appVersion: 1.9.0
home: https://github.com/cybertec-postgresql/CYBERTEC-pg-operator/tree/v0.7.0_changeAPI
description: Postgres Operator UI provides a graphical interface for a convenient database-as-a-service user experience
keywords:
- postgres
- operator
- ui
- cloud-native
- patroni
- spilo
maintainers:
- name: Zalando
  email: opensource@zalando.de
sources:
- https://github.com/cybertec-postgresql/CYBERTEC-pg-operator/tree/v0.7.0_changeAPI
engine: gotpl
