name: operator-e2e-tests

on: 
  pull_request:
  push:
    branches:
    - master

jobs:
  tests:
    name: End-2-End tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
      with:
<<<<<<< HEAD
          go-version: "^1.19.8"
=======
          go-version: "^1.18.9"
>>>>>>> 0ac5f58f (Switch gh workflows to go 1.18.9 (#2267))
    - name: Make dependencies
      run: make deps mocks
    - name: Code generation
      run: make codegen
    - name: Run unit tests
      run: make test
    - name: Run end-2-end tests
      run: make e2e
